import './globals.css'
import type { Metadata } from 'next'
import Provider from '@/providers/sessionProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <Provider >
          {children}
        </Provider>
      </body>
    </html>
  )
}
